

use_frameworks!

platform :ios, '9.0'

target 'ServiceComponents_Example' do
  pod 'ServiceComponents', :path => '../'
  pod 'Environment', :git => 'https://github.com/Wayment/ZY-Environment.git'

  target 'ServiceComponents_Tests' do
    inherit! :search_paths

    
  end
end
